name: PyTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: 13792000/fastoma:0.1

    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install PyTest
        run: |
          python -m pip install --upgrade pytest

      - name: Install dependencies
        run: |
          pip freeze
      
      - name: Run PyTest
        run: |
          python -m pytest -v